global:
  postgresql:
    auth:
      database: "usersdb"
      existingSecret: "db-secret"
      secretKeys:
        adminPasswordKey: "POSTGRESQL_PASSWORD"
        userPasswordKey: "DB_PASSWORD"
        usernameKey: "DB_USER"

primary:
  persistence:
    enabled: true
    size: 200Mi
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001

volumePermissions:
  enabled: true