apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: flyway/flyway:latest
        command: ["flyway", "-url=jdbc:postgresql://postgresql:5432/usersdb", "-user=$(DB_USER)", "-password=$(DB_PASSWORD)", "-schemas=public", "migrate"]
        envFrom:
        - secretRef:
            name: db-secret
      restartPolicy: Never
  backoffLimit: 1